name: developer_quest
description: Developer Quest Game


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  intl: ^0.17.0
  provider: ^6.0.3
  meta: ^1.7.0
  vector_math: ^2.1.2
  rive: ^0.9.0
  collection: ^1.16.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  git: ^2.0.0
  logging: ^1.0.2
  t_stats: ^3.0.0
  test: ^1.21.1


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/style_sphinx/
    - assets/images/
    - assets/flare/
    - assets/docs/code_chomper_alpha.dart
    - assets/docs/code_chomper_beta.dart

  fonts:
    - family: SpaceMonoRegular
      fonts:
        - asset: assets/fonts/SpaceMono-Regular.ttf
    - family: SpaceMonoBold
      fonts:
        - asset: assets/fonts/SpaceMono-Bold.ttf
    - family: RobotoCondensedBold
      fonts:
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: MontserratMedium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.otf
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
    - family: MontserratBold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.otf

